### ISSUE TITLE
新しい機能を追加する前に、CIを導入してみよう

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/python-dev-tutorial#9]
CIとは、 `Continuous Integration` の略となります。前回までにユニットテストを使った開発を導入してきましたが、CIを用いることで、ユニットテストを定期的に繰り返し実行することで、ユニットテスト実行タイミングから恣意性を減らし、バグの早期発見に貢献できます。

# 1. ローカルでターミナルからテストを実行できるようにする

今まではPyCharmから手動でテストを実行できるようにしていたが、自動でテストをするための準備として、ターミナルからテストを実行できるようにしましょう。

新しいブランチで `Makefile` を作り、`make` コマンドを使ってテストを実行できるようにします。
（簡単な例なので、 `make` を使わずに直接コマンドを実行してもかまいません）

> [make - ビルド作業を自動化するツールの使い方](https://linuxcommand.net/make/)

![image](https://user-images.githubusercontent.com/5868442/95367633-f127aa00-090f-11eb-83c1-6a673d6bbe66.png)

次のように、ターミナルからテストが実行できていることを確認しましょう。

![image](https://user-images.githubusercontent.com/5868442/95367768-1e745800-0910-11eb-8f98-ab28add246ea.png)

# 2. GitHub上で自動でテストが回るように設定する

`.github/workflows` の下に `tests.yml` を作り、次のようにテストの設定をする。このファイルを用意することで、[GitHub Actions](https://github.co.jp/features/actions) を使ってCIを実現することが出来ます。

```yml
name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: unittest
      run: |
        make unittest
    - name: doctest
      run: |
        make doctest
```

> 参照: [github.com/actions/setup-python](https://github.com/actions/setup-python)

# 3. PRを作り、CIが回っていることを確認してみよう

これまでと違い `All checks have passed` というメッセージが出ていることに注目しましょう。

![image](https://user-images.githubusercontent.com/5868442/95368635-55973900-0911-11eb-8ebd-daf04083a752.png)

`Details` からテスト結果の詳細を確認することができる。

![image](https://user-images.githubusercontent.com/5868442/95368674-647deb80-0911-11eb-9f16-0b0df9676137.png)

# 4. READMEにバッジをつけてみよう

`Actions` タブから実行しているCIに飛んで、 `Create status badge` をクリックします。

![image](https://user-images.githubusercontent.com/5868442/95369447-66947a00-0912-11eb-800b-58aa22f5387f.png)

表示されたメッセージをコピーしてREADMEに貼ります。

![image](https://user-images.githubusercontent.com/5868442/95369693-b8d59b00-0912-11eb-9440-ad1b3aad782f.png)

変更をコミットしてプッシュします。

# 5. PRをmainにマージしよう

実際に作成されたPRは #10 から確認できます。

# 目次

1. [プロジェクトを初期化しよう](https://github.com/sotetsuk/python-dev-tutorial/issues/1)
2. [仕様を決めて、ユニットテストを追加してみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/3)
3. [ユニットテストが通るように本体を実装してみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/5)
4. [(Optional) doctestを導入してみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/7)
5. **[現在]** [新しい機能を追加する前に、CIを導入してみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/9)
6. **[つぎ]** [新しい機能を追加してみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/11)
7. [ライブラリとして使えるようにしてみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/13)
8. [CLIツールとして使えるようにしてみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/15)
9. [(Optional) 便利な外部ライブラリをインストールして使ってみよう (Pytest編)](https://github.com/sotetsuk/python-dev-tutorial/issues/17)
10. [(Optional) 便利な外部ライブラリをインストールして使ってみよう (Click編)](https://github.com/sotetsuk/python-dev-tutorial/issues/19)
11. [型チェックを使ってみよう](https://github.com/sotetsuk/python-dev-tutorial/issues/40)
12. [しっかりとしたREADMEを書こう](https://github.com/sotetsuk/python-dev-tutorial/issues/22)
